Repository hoprnet/hopr-demo-seeds, pull requests merged in 2020-08, with the labels that each got.

#13 bump node version
  .github/workflows/nodejs.yml
  package.json
Labels: Patch Version, merge when passing

#15 Remove develop
  .github/workflows/nodejs.yml
  .github/workflows/publish.yaml
  .gitignore
  .nvmrc
  .yvmrc
  package.json
Labels: Minor Version, merge when passing

#16 ✨ Simpler workflow w/o version management
  .github/workflows/hopr.yaml
  .github/workflows/nodejs.yml
  .github/workflows/publish.yaml
Labels: Patch Version, merge when passing

#17 ✨ Simpler workflow w/o version management (pt2)
  .github/workflows/hopr.yaml
Labels: Patch Version, merge when passing

#18 ✨ Simpler workflow w/o version management (pt3)
  .github/workflows/hopr.yaml
Labels: Patch Version, merge when passing

#19 ✨ Simpler workflow w/o version management (pt4)
  .github/workflows/hopr.yaml
Labels: Patch Version, merge when passing

#20 ✨ Simpler workflow w/o version management (pt5)
  .github/workflows/hopr.yaml
Labels: Patch Version, merge when passing

#21 ✨ Simpler workflow w/o version management (pt6)
  .github/workflows/hopr.yaml
Labels: Patch Version, merge when passing

#22 ✨ Simpler workflow w/o version management (pt7)
  .github/workflows/hopr.yaml
  package.json
Labels: Patch Version, merge when passing

#34 Bump version
  .github/workflows/hopr.yaml
Labels: Patch Version

#35 Upper case
  .github/workflows/hopr.yaml
Labels: Patch Version

#36 Add token
  .github/workflows/hopr.yaml
Labels: Patch Version

#37 Workflow
  .github/workflows/hopr.yaml
  .github/workflows/release.yml
Labels: Patch Version

#38 setup node
  .github/workflows/hopr.yaml
  .github/workflows/release.yml
Labels: Patch Version

#39 setup node
  .github/workflows/hopr.yaml
Labels: Patch Version

#41 also publish to GPR
  .github/workflows/hopr.yaml
Labels: Patch Version
